stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/
    outs:
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv
  model_building:
    cmd: python src/model_building.py
    deps:
      - src/model_building.py
      - data/processed/train_processed.csv
    params:
      - model_building.ngram_range
      - model_building.max_features
      - model_building.learning_rate
      - model_building.max_depth
      - model_building.n_estimators
    outs:
      - models/tfidf_vectorizer.pkl
      - models/lgbm_model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/lgbm_model.pkl
      - models/tfidf_vectorizer.pkl
      - data/processed/test_processed.csv
    outs:
      - reports/confusion_matrix.png
      - reports/metrics.json