stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw/
    - src/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/processed
    - src/feature_engineering.py
    outs:
    - data/feature-engineered
    - models/tfidf_vectorizer.pkl
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/feature-engineered/train_tfidf.csv
    - src/model_building.py
    outs:
    - models/lgbm_model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/
    - data/processed/test_processed.csv
    outs:
    - reports/metrics.json